version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: grades
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/grades
    depends_on:
      - db
    ports:
      - "8000:8000"
